import { createHmac, randomInt, timingSafeEqual } from 'node:crypto';

/**
 * Organisation join codes.
 *
 * A join code is a bearer credential: whoever holds it can put themselves
 * inside an organisation and read its assessments. It is also, unavoidably,
 * something a person reads off a screen and types into another one — so it has
 * to be short enough to do that without mistakes, and long enough that
 * guessing is hopeless.
 *
 * The two requirements pull in opposite directions, and the resolution is the
 * alphabet below rather than a longer code. Removing the characters people
 * confuse (`O`/`0`, `I`/`1`/`L`) costs about a fifth of a bit per character and
 * removes most of the ways a correct code gets typed wrongly.
 *
 * Ten characters from a 30-character alphabet is a little over 49 bits. At a
 * hundred guesses a second against a live endpoint — far more than the rate
 * limiter permits — the expected time to find one code is measured in
 * millions of years. The rate limiter is what actually stops online guessing;
 * the entropy is what stops it being worth trying.
 */

/** No O, 0, I, 1 or L: the characters people transcribe wrongly. */
const ALPHABET = 'ABCDEFGHJKMNPQRSTUVWXYZ23456789';
const CODE_LENGTH = 10;

/** Displayed as KLY-XXXXX-XXXXX. Accepted in any spacing or case. */
const PREFIX = 'KLY';

export interface GeneratedJoinCode {
  /** The only time the plaintext exists. Show it once, store the hash. */
  code: string;
  /** HMAC-SHA256 under the server pepper, hex. This is what is stored. */
  hash: string;
  /** Last four characters, so an admin can tell two codes apart in a list. */
  hint: string;
}

/**
 * The pepper.
 *
 * Read lazily rather than at module load, so an installation that never uses
 * organisations does not fail to boot over a secret it does not need. When it
 * *is* needed and missing, this throws rather than falling back to a default —
 * a hardcoded fallback would mean every deployment shares a hash space, and a
 * code generated by one would be valid in another.
 */
function pepper(): string {
  const value = process.env.KLYRO_JOIN_CODE_PEPPER;

  if (!value || value.length < 32) {
    throw new Error(
      'KLYRO_JOIN_CODE_PEPPER is missing or too short. Set it to at least 32 random ' +
        'characters — join codes are hashed under it, and rotating it invalidates every ' +
        'code already issued.',
    );
  }

  return value;
}

/** Strips formatting so a pasted code matches a typed one. */
export function normaliseJoinCode(input: string): string {
  return (input ?? '')
    .toUpperCase()
    .replace(/[^A-Z0-9]/g, '')
    .replace(new RegExp(`^${PREFIX}`), '');
}

export function formatJoinCode(raw: string): string {
  const body = normaliseJoinCode(raw);
  return `${PREFIX}-${body.slice(0, 5)}-${body.slice(5)}`;
}

/**
 * Hashes a code for storage or lookup.
 *
 * Keyed rather than salted-and-slow. Bcrypt would be the right answer for a
 * user-chosen secret, where the threat is a dictionary; here the secret is 49
 * random bits, so there is no dictionary to run and the cost would buy nothing.
 * What it *would* cost is the index: a per-row salt means the join path cannot
 * look the code up, and would instead have to load every code in the table and
 * test each one.
 */
export function hashJoinCode(code: string): string {
  return createHmac('sha256', pepper()).update(normaliseJoinCode(code)).digest('hex');
}

/** Constant-time comparison, for the paths that compare two hashes directly. */
export function hashesMatch(a: string, b: string): boolean {
  const left = Buffer.from(a, 'utf8');
  const right = Buffer.from(b, 'utf8');
  if (left.length !== right.length) return false;
  return timingSafeEqual(left, right);
}

/**
 * Mints a new code.
 *
 * `randomInt` rather than `Math.random`, and rejection-free because the
 * alphabet length is passed as the bound — the crypto module handles the
 * modulo bias that a naive `% ALPHABET.length` would introduce.
 */
export function generateJoinCode(): GeneratedJoinCode {
  let body = '';
  for (let i = 0; i < CODE_LENGTH; i += 1) {
    body += ALPHABET[randomInt(ALPHABET.length)];
  }

  return {
    code: formatJoinCode(body),
    hash: hashJoinCode(body),
    hint: body.slice(-4),
  };
}

/** Whether a string could be a code at all, before any database work. */
export function looksLikeJoinCode(input: string): boolean {
  const body = normaliseJoinCode(input);
  if (body.length !== CODE_LENGTH) return false;
  return [...body].every((char) => ALPHABET.includes(char));
}
