import { beforeEach, describe, expect, it } from 'vitest';

import { createTestDb, type TestDb } from './harness';

/**
 * Who may write the plain-language summary.
 *
 * The summary is prose that appears under Klyro's letterhead, describing a
 * third party. `assessments` is append-only precisely because an owner who
 * could rewrite a finding could export the result as a Klyro report — and a
 * new column that the append-only trigger did not name would reopen exactly
 * that hole in a different shape: set `executive_summary` to any sentence,
 * then ask `/api/report/summary` to render it.
 *
 * Migration 0009 closes it on role rather than on privilege, because
 * table-level UPDATE cannot be narrowed here — Postgres only lets a column
 * privilege be revoked if it was granted as one, and revoking UPDATE outright
 * would take `contributes_to_benchmark` with it, which the append-only design
 * deliberately leaves writable.
 *
 * These tests are the reason to trust that. If they fail, Klyro will render
 * whatever an account holder types as its own assessment of somebody else.
 */

let db: TestDb;

beforeEach(async () => {
  if (db) await db.close();
  db = await createTestDb();
});

async function makeAssessment(owner: string): Promise<string> {
  const [row] = await db.asService().query<{ id: string }>(
    `insert into assessments
       (owner_user_id, created_by, domain, industry, region, composite_score, risk_level, coverage)
     values ($1, $1, 'example.test', 'Technology', 'Global', 72, 'Moderate Risk', 1)
     returning id`,
    [owner],
  );
  return row.id;
}

describe('the cached summary', () => {
  it('is writable by the service role', async () => {
    const alice = await db.createUser('alice@example.test');
    const id = await makeAssessment(alice);

    await db.asService().query(
      `update assessments set executive_summary = $2 where id = $1`,
      [id, JSON.stringify({ summary: 'The short version\nFine.', generated: true, generatedAt: new Date().toISOString() })],
    );

    const [row] = await db
      .asService()
      .query<{ executive_summary: { summary: string } | null }>(
        `select executive_summary from assessments where id = $1`,
        [id],
      );
    expect(row.executive_summary?.summary).toContain('The short version');
  });

  it('cannot be set by the owner of the assessment', async () => {
    const alice = await db.createUser('alice@example.test');
    const id = await makeAssessment(alice);

    // Alice passes the UPDATE policy — it is her row — and is still refused,
    // because the refusal is the trigger and not the policy.
    const message = await db.asUser(alice).denied(
      `update assessments set executive_summary = $2 where id = $1`,
      [id, JSON.stringify({ summary: 'This domain is perfectly safe.', generated: true })],
    );
    expect(message).toMatch(/generated by Klyro and cannot be set directly/i);
  });

  it('cannot be cleared by the owner either', async () => {
    const alice = await db.createUser('alice@example.test');
    const id = await makeAssessment(alice);
    await db
      .asService()
      .query(`update assessments set executive_summary = $2 where id = $1`, [
        id,
        JSON.stringify({ summary: 'Written by Klyro.', generated: true }),
      ]);

    const message = await db
      .asUser(alice)
      .denied(`update assessments set executive_summary = null where id = $1`, [id]);
    expect(message).toMatch(/cannot be set directly/i);
  });

  it('leaves the column readable to whoever may read the assessment', async () => {
    const alice = await db.createUser('alice@example.test');
    const id = await makeAssessment(alice);
    await db
      .asService()
      .query(`update assessments set executive_summary = $2 where id = $1`, [
        id,
        JSON.stringify({ summary: 'Readable.', generated: true }),
      ]);

    const rows = await db
      .asUser(alice)
      .query<{ executive_summary: { summary: string } | null }>(
        `select executive_summary from assessments where id = $1`,
        [id],
      );
    expect(rows[0].executive_summary?.summary).toBe('Readable.');
  });

  it('is not readable by anybody else', async () => {
    const alice = await db.createUser('alice@example.test');
    const bob = await db.createUser('bob@example.test');
    const id = await makeAssessment(alice);
    await db
      .asService()
      .query(`update assessments set executive_summary = $2 where id = $1`, [
        id,
        JSON.stringify({ summary: 'Alice only.', generated: true }),
      ]);

    const rows = await db
      .asUser(bob)
      .query(`select executive_summary from assessments where id = $1`, [id]);
    expect(rows).toHaveLength(0);
  });

  it('still refuses every observation the assessment recorded', async () => {
    // The new clause must not have loosened the original rule.
    const alice = await db.createUser('alice@example.test');
    const id = await makeAssessment(alice);

    /*
     * Each value must genuinely differ from what the row holds. The first
     * version of this test set `findings` to `'[]'::jsonb`, which is the
     * column's default — `is distinct from` saw no change, the trigger
     * correctly did nothing, and the test read that as the guard being absent.
     */
    for (const [column, value] of [
      ['composite_score', '100'],
      ['findings', `'[{"id":"invented"}]'::jsonb`],
      ['categories', `'[{"key":"dns"}]'::jsonb`],
      ['domain', `'other.test'`],
      ['coverage', '0.1'],
    ] as const) {
      const message = await db
        .asUser(alice)
        .denied(`update assessments set ${column} = ${value} where id = $1`, [id]);
      expect(message).toMatch(/cannot be edited/i);
    }
  });

  it('still permits the one column that expresses intent', async () => {
    const alice = await db.createUser('alice@example.test');
    const id = await makeAssessment(alice);

    const rows = await db
      .asUser(alice)
      .query(
        `update assessments set contributes_to_benchmark = true where id = $1 returning id`,
        [id],
      );
    expect(rows).toHaveLength(1);
  });
});
