-- 0009 — The cached plain-language summary.
--
-- `POST /api/report/summary` turns an assessment into a one-page document
-- written for a non-technical reader. Generating it costs a model call, and
-- the same assessment is downloaded more than once, so the result is cached on
-- the row it describes.
--
-- The interesting part is not the column, it is who may write it.
--
-- `assessments` is append-only by trigger because a mutable assessment is
-- worthless as evidence, and because an owner who could rewrite a finding
-- could export the result as a Klyro report. A summary is prose that appears
-- under the same letterhead, so it inherits exactly that problem: a column
-- the trigger does not name is a column an owner can put any sentence into,
-- and `/api/report/summary` would then render that sentence as Klyro's
-- assessment of a third party.
--
-- Table-level UPDATE cannot be narrowed away here — Postgres only lets a
-- column privilege be revoked if it was granted as a column privilege, and
-- these were granted table-wide. Revoking UPDATE outright would also remove
-- the one legitimate client write on this table, `contributes_to_benchmark`,
-- which is the column the append-only design deliberately leaves writable
-- because it expresses intent rather than observation.
--
-- So the trigger decides, on role. The summary is written by the scan and
-- report routes through the service role; every other caller may read it and
-- may not set it.

alter table assessments
  add column if not exists executive_summary jsonb;

comment on column assessments.executive_summary is
  'Cached plain-language summary: { summary, generated, generatedAt, toolVersion }. '
  'Written only by the service role — see app.assessments_are_append_only().';

/*
 * Same trigger as 0006, with one clause added.
 *
 * Recreated in full rather than patched, so the file that owns this rule reads
 * as the whole rule rather than as a delta against another migration.
 */
create or replace function app.assessments_are_append_only() returns trigger
  language plpgsql
as $$
begin
  if new.domain          is distinct from old.domain
     or new.composite_score is distinct from old.composite_score
     or new.risk_level     is distinct from old.risk_level
     or new.coverage       is distinct from old.coverage
     or new.tool_version   is distinct from old.tool_version
     or new.scanned_at     is distinct from old.scanned_at
     or new.category_scores is distinct from old.category_scores
     or new.categories      is distinct from old.categories
     or new.findings        is distinct from old.findings
     or new.inventory       is distinct from old.inventory
     or new.benchmark       is distinct from old.benchmark
     or new.owner_user_id   is distinct from old.owner_user_id
     or new.owner_org_id    is distinct from old.owner_org_id
  then
    raise exception
      'An assessment records what was observed at a point in time and cannot be edited. Run a new assessment instead.'
      using errcode = 'check_violation';
  end if;

  -- The summary is generated from the row's own findings by Klyro's server.
  -- A client that could write it could publish arbitrary prose about a third
  -- party as a Klyro document, which is the same objection that makes the
  -- columns above immutable.
  if new.executive_summary is distinct from old.executive_summary
     and current_user <> 'service_role'
  then
    raise exception
      'The plain-language summary is generated by Klyro and cannot be set directly.'
      using errcode = 'check_violation';
  end if;

  return new;
end;
$$;

drop trigger if exists on_assessment_update_append_only on assessments;
create trigger on_assessment_update_append_only
  before update on assessments
  for each row execute function app.assessments_are_append_only();
